version: "3"
services:
  mongodb:
    image: mongo:4.0.0
    container_name: "mongodb"
    ports:
      - 27019:27090
    command: --smallfiles
  app:
    build: .
    image: app/muzix
    ports:
      - 8080:8080
      - 8102:8111
    links:
      - mongodb
